# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rentalbikes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://rentalbikes.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e9de0a54d0484176bfcb035d61ae3e76 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ebde41c404524e5d907181efd8adec30 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rentalbikes.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9de0a54d0484176bfcb035d61ae3e76 }}/rentalbikes:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rentalbikes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7c0cab447e9c4430bf18b83b176b402a }}
        images: 'rentalbikes.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9de0a54d0484176bfcb035d61ae3e76 }}/rentalbikes:${{ github.sha }}'